development:
  password: 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
  theme_id: "123866349727"
  store: www-rubaiyatfashion-com.myshopify.com
production:
  password: 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
  theme_id: "123866349727"
  store: www-rubaiyatfashion-com.myshopify.com
